package com.afrid.tag_register.bean;

public class ServiceTWarehouseLinenKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_WAREHOUSE_LINEN.WAREHOUSE_ID
     *
     * @mbggenerated
     */
    private Integer warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_WAREHOUSE_LINEN.LINEN_ID
     *
     * @mbggenerated
     */
    private Integer linenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_WAREHOUSE_LINEN.WAREHOUSE_ID
     *
     * @return the value of SERVICE_T_WAREHOUSE_LINEN.WAREHOUSE_ID
     *
     * @mbggenerated
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_WAREHOUSE_LINEN.WAREHOUSE_ID
     *
     * @param warehouseId the value for SERVICE_T_WAREHOUSE_LINEN.WAREHOUSE_ID
     *
     * @mbggenerated
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_WAREHOUSE_LINEN.LINEN_ID
     *
     * @return the value of SERVICE_T_WAREHOUSE_LINEN.LINEN_ID
     *
     * @mbggenerated
     */
    public Integer getLinenId() {
        return linenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_WAREHOUSE_LINEN.LINEN_ID
     *
     * @param linenId the value for SERVICE_T_WAREHOUSE_LINEN.LINEN_ID
     *
     * @mbggenerated
     */
    public void setLinenId(Integer linenId) {
        this.linenId = linenId;
    }
}