package com.afrid.tag_register.bean;

public class ServiceTTrain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_TRAIN.TRAIN_CODE
     *
     * @mbggenerated
     */
    private String trainCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_TRAIN.TRAIN_NAME
     *
     * @mbggenerated
     */
    private String trainName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_TRAIN.TRAIN_CODE
     *
     * @return the value of SERVICE_T_TRAIN.TRAIN_CODE
     *
     * @mbggenerated
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_TRAIN.TRAIN_CODE
     *
     * @param trainCode the value for SERVICE_T_TRAIN.TRAIN_CODE
     *
     * @mbggenerated
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_TRAIN.TRAIN_NAME
     *
     * @return the value of SERVICE_T_TRAIN.TRAIN_NAME
     *
     * @mbggenerated
     */
    public String getTrainName() {
        return trainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_TRAIN.TRAIN_NAME
     *
     * @param trainName the value for SERVICE_T_TRAIN.TRAIN_NAME
     *
     * @mbggenerated
     */
    public void setTrainName(String trainName) {
        this.trainName = trainName;
    }
}