package com.afrid.tag_register.bean;

public class ServiceTLinen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_LINEN.LINEN_ID
     *
     * @mbggenerated
     */
    private Integer linenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_LINEN.LINEN_NAME
     *
     * @mbggenerated
     */
    private String linenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_LINEN.PARENT_ID
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_LINEN.LINEN_ID
     *
     * @return the value of SERVICE_T_LINEN.LINEN_ID
     *
     * @mbggenerated
     */
    public Integer getLinenId() {
        return linenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_LINEN.LINEN_ID
     *
     * @param linenId the value for SERVICE_T_LINEN.LINEN_ID
     *
     * @mbggenerated
     */
    public void setLinenId(Integer linenId) {
        this.linenId = linenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_LINEN.LINEN_NAME
     *
     * @return the value of SERVICE_T_LINEN.LINEN_NAME
     *
     * @mbggenerated
     */
    public String getLinenName() {
        return linenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_LINEN.LINEN_NAME
     *
     * @param linenName the value for SERVICE_T_LINEN.LINEN_NAME
     *
     * @mbggenerated
     */
    public void setLinenName(String linenName) {
        this.linenName = linenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_LINEN.PARENT_ID
     *
     * @return the value of SERVICE_T_LINEN.PARENT_ID
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_LINEN.PARENT_ID
     *
     * @param parentId the value for SERVICE_T_LINEN.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}