package com.afrid.tag_register.bean;

public class ServiceTWarehouseLinen extends ServiceTWarehouseLinenKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICE_T_WAREHOUSE_LINEN.LINEN_NUM
     *
     * @mbggenerated
     */
    private Integer linenNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICE_T_WAREHOUSE_LINEN.LINEN_NUM
     *
     * @return the value of SERVICE_T_WAREHOUSE_LINEN.LINEN_NUM
     *
     * @mbggenerated
     */
    public Integer getLinenNum() {
        return linenNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICE_T_WAREHOUSE_LINEN.LINEN_NUM
     *
     * @param linenNum the value for SERVICE_T_WAREHOUSE_LINEN.LINEN_NUM
     *
     * @mbggenerated
     */
    public void setLinenNum(Integer linenNum) {
        this.linenNum = linenNum;
    }
}